/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Patients model module.
 * @module model/Patients
 * @version 1.0.0
 */
class Patients {
    /**
     * Constructs a new <code>Patients</code>.
     * @alias module:model/Patients
     * @param pname {String} 
     * @param page {String} 
     */
    constructor(pname, page) { 
        
        Patients.initialize(this, pname, page);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pname, page) { 
        obj['pname'] = pname;
        obj['page'] = page;
    }

    /**
     * Constructs a <code>Patients</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Patients} obj Optional instance to populate.
     * @return {module:model/Patients} The populated <code>Patients</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Patients();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('pname')) {
                obj['pname'] = ApiClient.convertToType(data['pname'], 'String');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Patients.prototype['_id'] = undefined;

/**
 * @member {String} pname
 */
Patients.prototype['pname'] = undefined;

/**
 * @member {String} page
 */
Patients.prototype['page'] = undefined;






export default Patients;

